# Generated by Django 5.0.1 on 2024-01-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('tipo_material', models.CharField(max_length=45)),
                ('devolucion', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('lugar', models.CharField(max_length=45)),
                ('emergencia', models.BooleanField(default=False)),
                ('fk_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.material')),
            ],
            options={
                'db_table': 'Obra',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('oficina', models.CharField(blank=True, max_length=45, null=True)),
                ('carta_de_termino', models.CharField(blank=True, max_length=45, null=True)),
                ('fk_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.obra')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
    ]
