# Generated by Django 5.0.1 on 2024-02-12 01:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('lugar', models.CharField(max_length=45)),
                ('si_emergencia', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('si_finalizo', models.BooleanField(default=False)),
                ('tipo_obra', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('idMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('descripcion', models.CharField(max_length=45)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RetiroMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_retirada', models.IntegerField(default=0)),
                ('fecha_retiro', models.DateField(default=datetime.date.today)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros_material', to='usuario.obra')),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipomaterial')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField(default=0)),
                ('fecha_devolucion', models.DateField(default=datetime.date.today)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_material', to='usuario.obra')),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipomaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('orden_factura', models.AutoField(primary_key=True, serialize=False)),
                ('num_factura', models.CharField(max_length=100, unique=True)),
                ('num_nota_credit', models.CharField(max_length=100, unique=True)),
                ('val_neto_fact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('val_neto_nc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='usuario.obra')),
            ],
            options={
                'indexes': [models.Index(fields=['obra'], name='index_obra'), models.Index(fields=['num_factura'], name='index_num_factura'), models.Index(fields=['num_nota_credit'], name='index_num_nota_credit')],
            },
        ),
    ]
