# Generated by Django 5.0.1 on 2024-02-06 03:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='obra',
            name='fk_material',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='emergencia',
            new_name='si_devuelve',
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_termino',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='obra',
            name='si_emergencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obra',
            name='si_finalizo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obra',
            name='si_retira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obra',
            name='tipo_obra',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterModelTable(
            name='obra',
            table=None,
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('orden_factura', models.AutoField(primary_key=True, serialize=False)),
                ('num_factura', models.CharField(max_length=100, unique=True)),
                ('num_nota_credit', models.CharField(max_length=100, unique=True)),
                ('val_neto_fact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('val_neto_nc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='usuario.obra')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirado', models.IntegerField(default=0)),
                ('devuelto', models.IntegerField(default=0)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='usuario.obra')),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipomaterial')),
            ],
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['obra'], name='index_obra'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['num_factura'], name='index_num_factura'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['num_nota_credit'], name='index_num_nota_credit'),
        ),
        migrations.AlterUniqueTogether(
            name='materialobra',
            unique_together={('obra', 'tipo_material')},
        ),
    ]
