# Generated by Django 5.0.1 on 2024-02-15 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerUsoDia',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('si_ingresa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha'], name='index_fecha'), models.Index(fields=['usuario'], name='index_usuario')],
            },
        ),
    ]
