# Generated by Django 5.0.1 on 2024-02-16 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_primerusodia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id_emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('lugar', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='obra',
            name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='si_emergencia',
        ),
        migrations.AddField(
            model_name='devolucionmaterial',
            name='conductor',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='devolucionmaterial',
            name='nota_de_pedido',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='obra',
            name='etapa',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='obra',
            name='id_obra',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obra',
            name='si_finalizo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
